name: ubuntu-20.04
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      # Needs to lock glibc version to 2.31, ubuntu 20.04 has glibc 2.31
      image: ubuntu:20.04
    timeout-minutes: 30
    steps:
      - name: apt-get
        run: |
          apt-get update
          apt-get install -y unzip curl git autoconf build-essential ca-certificates
      - name: check glibc version
        run: ldd --version
      - name: default working directory
        run: pwd
