name: ubuntu-20.04
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      # Needs to lock glibc version to 2.31, ubuntu 20.04 has glibc 2.31
      image: ubuntu:20.04
    timeout-minutes: 30
    steps:
      - name: apt-get
        run: |
          apt-get update
          apt-get install -y unzip curl git autoconf build-essential ca-certificates
      - name: apt-get (.NET)
        run: |
          apt-get install -y libicu66
      - name: check glibc version
        run: ldd --version
      - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: '9.0.x'
      - name: check dotnet version
        run: dotnet --list-sdks
